-- 코드를 입력하세요
SELECT f.FLAVOR
FROM FIRST_HALF f
 JOIN (SELECT FLAVOR, INGREDIENT_TYPE
         FROM ICECREAM_INFO
        WHERE INGREDIENT_TYPE = 'fruit_based') ice
   ON f.FLAVOR = ice.FLAVOR
WHERE f.TOTAL_ORDER > 3000
ORDER BY f.TOTAL_ORDER desc;


